Repository andela/ah-kgl-wakanda-frontend, pull requests merged in 2019-07, with the labels that each got.

#28 #165020086 Add comment functionalities
  cypress/integration/articles/create.spec.js
  cypress/integration/articles/edit.spec.js
  cypress/integration/articles/single.spec.js
  src/Containers/Article/Single/singleArticle.jsx
  src/Containers/Article/Single/singleArticle.scss
  src/__test__/containers/articles/singleArticle.test.js
  src/actionTypes/article.js
  src/actions/article.js
  src/reducers/article.js
Labels: All checks ✅, REVIEWED :+1:

#33 Feature(Pagination): pagination support for article
  cypress/integration/home.spec.js
  cypress/integration/userArticles.spec.js
  package.json
  src/Components/Articles/Article.jsx
  src/Components/Articles/Trendings.jsx
  src/Components/Rating/Rating.scss
  src/Containers/Article/Single/singleArticle.jsx
  src/Containers/Article/Single/singleArticle.scss
  src/Containers/Home/Home.jsx
  src/Containers/UserArticles/UserArticles.jsx
  src/__test__/containers/Home.test.js
  src/__test__/containers/userArticles.test.js
  src/actionTypes/fetchArticles.js
  src/actions/fetchArticles.js
  src/helpers/getRatings.js
  src/reducers/fetchArticles.js
Labels: REVIEWED :+1:

#35 Fixes bugs
  src/Components/Articles/Article.jsx
  src/Components/Articles/TopArticle.jsx
  src/Components/Articles/Trendings.jsx
  src/Components/Common/Profile/DropdownItem.jsx
  src/Components/Common/Profile/ProfileDropdown.scss
  src/Components/Common/SearchBox/SearchBox.jsx
  src/Components/NavBar/NavBar.jsx
  src/Components/Routes.jsx
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.scss
  src/Containers/Article/Single/singleArticle.scss
  src/Containers/Home/Home.jsx
  src/Containers/Profile/Profile.scss
  src/Containers/Profile/profileContainer.jsx
  src/Containers/Search/ResultCard.scss
  src/__test__/component/Articles/Article.test.js
  src/__test__/component/Articles/TopArticle.test.js
  src/__test__/component/Articles/Trendings.test.js
  src/__test__/component/NavBar.test.js
  src/__test__/containers/Home.test.js
  src/actionTypes/system.js
  src/actions/profileActions.js
  src/actions/system.js
  src/actions/userInfo.js
  src/api/wakanda.js
  src/helpers/getRatings.js
  src/reducers/currentUser.js
  src/store/initialState.js
Labels: All checks ✅, WAITING FOR REVIEW :1st_place_medal:

#36 #165020097 Implement article bookmarking and unbookmarking
  cypress/integration/articles/single.spec.js
  package.json
  src/Components/Articles/Article.jsx
  src/Components/Articles/TopArticle.jsx
  src/Components/Articles/Trendings.jsx
  src/Components/Common/Bookmark/Bookmark.jsx
  src/Components/Common/Profile/DropdownItem.jsx
  src/Components/Common/Profile/ProfileDropdown.jsx
  src/Components/Routes.jsx
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.scss
  src/Containers/Article/Bookmarked/bookmarked.jsx
  src/Containers/Article/Bookmarked/bookmarked.scss
  src/Containers/Article/Single/singleArticle.jsx
  src/Containers/Article/Single/singleArticle.scss
  src/Containers/Home/Home.jsx
  src/Containers/Home/Home.scss
  src/Containers/UserArticles/UserArticles.jsx
  src/__test__/actions/bookmark.test.js
  src/__test__/actions/getBookmarked.test.js
  src/__test__/actions/unbookmark.test.js
  src/__test__/component/Articles/Article.test.js
  src/__test__/component/Articles/TopArticle.test.js
  src/__test__/component/Articles/Trendings.test.js
  src/__test__/containers/Home.test.js
  src/__test__/containers/articles/singleArticle.test.js
  src/__test__/containers/userArticles.test.js
  src/__test__/reducers/bookmark.test.js
  src/__test__/reducers/unbookmark.test.js
  src/__test__/reducers/viewBookmarked.test.js
  src/actionTypes/bookmark.js
  src/actionTypes/viewBookmarked.js
  src/actions/bookmark.js
  src/actions/getBookmarked.js
  src/actions/unbookmark.js
  src/assets/sass/global.scss
  src/helpers/getRatings.js
  src/reducers/bookmark.js
  src/reducers/index.js
  src/reducers/unbookmark.js
  src/reducers/viewBookmarked.js
Labels: WAITING FOR REVIEW :1st_place_medal:

#40 #167166967 Display button to go back to home page on mobile
  src/Components/NavBar/NavBar.jsx
  src/Components/NavBar/NavBar.scss
  src/__test__/component/NavBar.test.js
Labels: All checks ✅, REVIEWED :+1:
