Repository andela/ah-kgl-wakanda-frontend, pull requests merged in 2019-06, with the labels that each got.

#7 #166470806 setup heroku
  Procfile
  package.json
  server.js
Labels: CHORE

#10 #166575772 add a reusable input component
  .eslintrc
  .hound.yml
  babel.config.js
  jest.config.js
  package.json
  src/Components/Common/input/input.jsx
  src/Components/Common/input/input.scss
  src/Containers/Home/Home.jsx
  src/__test--/component/Header.test.js
  src/__test--/test.test.js
  src/__test__/component/common/input.test.js
  src/__test__/test.test.js
  src/setupTests.js
Labels: CHORE, REVIEWED :+1:

#8 #166575755 Adding a dynamic button
  jest.config.js
  package.json
  src/Components/Common/Button/Button.jsx
  src/Components/Common/Button/Button.scss
  src/__mocks__/fileMock.js
  src/__test--/test.test.js
  src/__test__/component/common/button.test.js
  src/assets/images/facebook.png
  src/assets/images/google.png
  src/assets/images/twitter.png
Labels: Merge me :(

#13 #165020080 enable user to login
  .eslintrc
  cypress/integration/login.spec.js
  cypress/integration/sample.spec.js
  cypress/videos/login.spec.js.mp4
  cypress/videos/sample.spec.js.mp4
  package.json
  src/Components/Common/Button/Button.jsx
  src/Components/Common/Button/Button.scss
  src/Components/Common/input/input.jsx
  src/Components/Routes.jsx
  src/Containers/Home/Home.jsx
  src/Containers/Login/login.jsx
  src/Containers/Login/login.scss
  src/__mocks__/axios.js
  src/__mocks__/styleMock.js
  src/__test__/component/common/button.test.js
  src/__test__/component/common/input.test.js
  src/__test__/component/containers/login.test.js
  src/actionTypes/login.js
  src/actions/login.js
  src/api/wakanda.js
  src/assets/images/avatar-1606916_960_720.png
  src/assets/images/img-article.png
  src/assets/images/logo_ah_2.png
  src/assets/images/undraw_Memory_storage_reh0.svg
  src/assets/images/undraw_authentication_fsn5.svg
  src/assets/images/undraw_login_jdch.svg
  src/assets/images/undraw_my_password_d6kg.svg
  src/assets/sass/global.scss
  src/index.js
  src/reducers/currentUser.js
  src/reducers/index.js
  src/reducers/login.js
  src/reducers/name.js
  src/store/initialState.js
Labels: All checks ✅, REVIEWED :+1:

#15 #165020078 User sign up page
  .env.example
  .travis.yml
  cypress/integration/sample.spec.js
  cypress/integration/signup.spec.js
  cypress/videos/sample.spec.js.mp4
  cypress/videos/signup.spec.js.mp4
  src/Components/Common/input/input.jsx
  src/Components/Header/Header.jsx
  src/Components/Header/Header.scss
  src/Components/Routes.jsx
  src/Containers/Home/Home.jsx
  src/Containers/Home/Home.scss
  src/Containers/Signup/Signup.jsx
  src/Containers/Signup/Signup.scss
  src/__test--/test.test.js
  src/__test__/containers/signup.test.js
  src/actionTypes/index.js
  src/actionTypes/signupTypes.js
  src/actions/changeName.js
  src/actions/signupActions.js
  src/assets/images/signup-illustration.svg
  src/index.js
  src/reducers/index.js
  src/reducers/signupReducer.js
  src/store/initialState.js
Labels: All checks ✅, Merge me :(, REVIEWED :+1:

#14 #166575803 Build the NavBar component and its children component
  .eslintignore
  .gitignore
  jest.config.js
  package.json
  src/Components/Common/Logo/Logo.jsx
  src/Components/Common/Logo/Logo.scss
  src/Components/Common/MiniAccount/MiniAccount.jsx
  src/Components/Common/MiniAccount/MiniAccount.scss
  src/Components/Common/NotifIcon/NotifIcon.jsx
  src/Components/Common/NotifIcon/NotifIcon.scss
  src/Components/Common/SearchBox/SearchBox.jsx
  src/Components/Common/SearchBox/SearchBox.scss
  src/Components/NavBar/NavBar.jsx
  src/Components/NavBar/NavBar.scss
  src/Components/Routes.jsx
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.scss
  src/__test__/actions/toggleSideNav.test.js
  src/__test__/component/NavBar.test.js
  src/__test__/component/__snapshots__/NavBar.test.js.snap
  src/__test__/reducers/navbar.test.js
  src/__test__/store/index.test.js
  src/actionTypes/index.js
  src/actions/toggleSideNav.js
  src/api/wakanda.js
  src/assets/img/blank_profile_pic.png
  src/assets/img/logo_ah.png
  src/assets/sass/global.scss
  src/assets/sass/mixin.scss
  src/paths.js
  src/reducers/index.js
  src/reducers/navbar.js
  src/store/initialState.js
Labels: REVIEWED :+1:

#21 #166575803 Fix major problem in the Navbar component
  src/Components/Common/Logo/Logo.scss
  src/Components/Common/MiniAccount/MiniAccount.jsx
  src/Components/Common/MiniAccount/MiniAccount.scss
  src/Components/Common/NotifIcon/NotifIcon.jsx
  src/Components/Common/NotifIcon/NotifIcon.scss
  src/Components/Common/Profile/DropdownItem.jsx
  src/Components/Common/Profile/ProfileDropdown.jsx
  src/Components/Common/Profile/ProfileDropdown.scss
  src/Components/Common/SearchBox/SearchBox.jsx
  src/Components/Common/SearchBox/SearchBox.scss
  src/Components/NavBar/NavBar.jsx
  src/Components/NavBar/NavBar.scss
  src/Components/Routes.jsx
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.scss
  src/__test__/component/NavBar.test.js
  src/__test__/component/SideBar.test.js
  src/__test__/component/common/SearchBox.test.js
  src/__test__/component/common/__snapshots__/SearchBox.test.js.snap
  src/__test__/component/common/profileDropdown.test.js
  src/actions/toggleSideNav.js
  src/assets/sass/global.scss
  src/paths.js
  src/reducers/index.js
  src/reducers/navbar.js
  src/store/initialState.js
Labels: REVIEWED :+1:, bug, enhancement

#24 #165020084 create and view an article
  .eslintrc
  cypress/integration/articles/create.spec.js
  package.json
  public/index.html
  src/Components/Common/Button/Button.jsx
  src/Components/Common/input/input.jsx
  src/Components/NavBar/NavBar.jsx
  src/Components/Routes.jsx
  src/Components/SideBar/SideBar.jsx
  src/Components/SideBar/SideBar.scss
  src/Containers/Article/Create/createArticle.jsx
  src/Containers/Article/Create/createArticle.scss
  src/Containers/Article/Single/singleArticle.jsx
  src/Containers/Article/Single/singleArticle.scss
  src/Containers/NotFound/NotFound.css
  src/Containers/NotFound/NotFound.jsx
  src/__test__/containers/articles/create.test.js
  src/__test__/containers/articles/singleArticle.test.js
  src/actionTypes/article.js
  src/actionTypes/index.js
  src/actionTypes/system.js
  src/actions/article.js
  src/actions/userInfo.js
  src/api/wakanda.js
  src/assets/images/icons/dark-star.png
  src/assets/images/icons/delete.png
  src/assets/images/icons/edit.png
  src/assets/images/icons/empty-star-dark.png
  src/assets/images/icons/empty-star.png
  src/assets/images/icons/light-star.png
  src/assets/images/image-display.jpg
  src/assets/images/profile-boy.png
  src/assets/images/profile-girl.png
  src/assets/sass/global.scss
  src/paths.js
  src/reducers/article.js
  src/reducers/currentUser.js
  src/reducers/index.js
  src/reducers/system.js
  src/store/initialState.js
Labels: REVIEWED :+1:
